### ISSUE TITLE
Hall effect sensor pinout comparison to InFiDEL

### ISSUE THREAD

**Issue by cad435** [SasaKaranovic/winfidel-sensor#3]
It should be noted somewhere, that the hall sensor should be mounted the other way round, compared to the original INFIDEL Sensor.

Top-PCB is the original, bottom PCB is WinFIDEL

![image](https://github.com/SasaKaranovic/winfidel-sensor/assets/16453385/a72dd934-10f9-4087-9465-8100c94a8d3e)

Therefore the Hall-effect sensor must be glued in "upside down" compared to the original.

 - cad435

**Comment by SasaKaranovic** [comment]
Hey @cad435 

Please note that while WInFiDEL is inspired by InFiDEL, it is not identical, obviously.
If you flip the WInFiDEL board, you should see the 3V3, GND and OUT markings for that IC.

There are two ways you can figure out which components is on which side.
- Manually: If you use silkscreen as your guide, there is silkscreen on top AND bottom side. On the bottom side there is silkscreen that indicates the sensor pinout and also U3 that indicates that hall effect sensor is on the bottom.
- Production: Pick and Place file indicates that the U3 is on the bottom side.

![WinFidel-pinout](https://github.com/SasaKaranovic/winfidel-sensor/assets/75916/97626dd6-d046-43b7-acea-98d055d54152)

**Comment by SasaKaranovic** [comment]
I don't have the InFiDEL sensor but just looked at some pictures and it looks like the sensor is mounted in the exact same way on the exact same side.

Can you clarify what do you mean by `the hall sensor should be mounted the other way round` ?
Are you using the Hall effect sensor that is specified by WInFiDEL design (ie `DRV5055A3`/`DRV5055A2`/`DRV5055A1`) ?

**Comment by cad435** [comment]
Yes, I use a DRV5505.

So basically I hat some IFIDELS laying around and "upgraded" them with WinFIDEL.

The problem is as followed:
While INFIDEL hast the VIN pin of the hall-Sensor on the right pin (in my top picture), WinFIDEL has the VIN pin on the Left side.

So in order to upgrade from INFIDEL to WinFIDEL I had to remove the HALL sensor and glue a new one in, to match the Pinout.
Like, I have do apply the CA-Glue on the other side of the sensor compared to INFIDEL.

And it works now 👌🏼


And yes I'm aware, that this is only inspired, not a replacement.

To be fair I hoped that it is completely compatible :)

**Comment by SasaKaranovic** [comment]
Glad to hear that you got it working.

I'm not sure where did this suggestion that WInFiDEL and InFiDEL are pin-to-pin compatible came from?
These are two different designs that share some design features but that's pretty much it.
